detecting if server's running now

diff --git a/opt/cs50/phpliteadmin/bin/phpliteadmin b/opt/cs50/phpliteadmin/bin/phpliteadmin
--- a/opt/cs50/phpliteadmin/bin/phpliteadmin
+++ b/opt/cs50/phpliteadmin/bin/phpliteadmin
@@ -52,17 +52,23 @@ cat > "$temp/index.php" <<EOF
 ?>
 EOF
 
+# check if already running
+if curl -I http://localhost:8081/ > /dev/null 2>&1; then
+    echo "Could not start phpLiteAdmin. Is it running in another terminal window?"
+    exit 1
+fi
+
 # serve copy
 php -S 0.0.0.0:8081 -t "$temp" > /dev/null 2>&1 &
 pid=$!
 if command -v hostname50 > /dev/null 2>&1; then
     hostname=$(hostname50)
-    echo c9 exec browser "https://$hostname:8081/"
+    echo c9 exec browser "https://$hostname:8081/?pin=$password"
     echo "Running phpLiteAdmin at https://$hostname:8081/?pin=$password"
 else
     echo "Running phpLiteAdmin at http://localhost:8081/?pin=$password"
 fi
-echo "Exit with ctrl-c."
+echo -n "Exit with ctrl-c..."
 
 # listen for ctrl-c
 # http://stackoverflow.com/a/5722850
@@ -70,10 +76,6 @@ trap "{ kill -9 $pid; wait $pid 2> /dev/null; echo; }" INT
 
 # wait for server to exit
 wait $pid
-if [[ $? -eq 1 ]]; then
-    echo "Could not start phpLiteAdmin. Is it running in another terminal window?"
-    exit 1
-fi
 
 # remove copy
 rm -rf "$temp"
